#!/bin/bash
#
# Neo N3 Price Oracle Manual Deployment Guide
#

echo "🚀 Neo N3 Price Oracle Deployment Guide"
echo "======================================"
echo ""
echo "Contract Details:"
echo "  Name: PriceFeed.Oracle"
echo "  Expected Hash: 0xc14ffc3f28363fe59645873b28ed3ed8ccb774cc"
echo "  Deployment Cost: ~10.002 GAS"
echo "  Account: NTmHjwiadq4g3VHpJ5FQigQcD4fF5m8TyX"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 1: Neo-CLI (Recommended)"
echo "-------------------------------"
echo ""
echo "1. Download Neo-CLI:"
echo "   wget https://github.com/neo-project/neo-cli/releases/download/v3.6.2/neo-cli-linux-x64.zip"
echo "   unzip neo-cli-linux-x64.zip"
echo "   cd neo-cli"
echo ""
echo "2. Start Neo-CLI:"
echo "   ./neo-cli"
echo ""
echo "3. Create and setup wallet:"
echo "   neo> create wallet deploy.json"
echo "   neo> open wallet deploy.json"
echo "   neo> import key $MASTER_WIF"
echo ""
echo "4. Deploy contract:"
echo "   neo> deploy $(pwd)/src/PriceFeed.Contracts/PriceFeed.Oracle.nef $(pwd)/src/PriceFeed.Contracts/PriceFeed.Oracle.manifest.json"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 2: NeoLine Browser Extension"
echo "-----------------------------------"
echo ""
echo "1. Install NeoLine: https://neoline.io/"
echo "2. Import private key"
echo "3. Switch to TestNet"
echo "4. Go to: https://neoline.io/deploy"
echo "5. Upload files from: $(pwd)/deployment-files/"
echo "6. Confirm deployment"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "AFTER DEPLOYMENT:"
echo "-----------------"
echo ""
echo "1. Initialize contract:"
echo "   invoke 0xc14ffc3f28363fe59645873b28ed3ed8ccb774cc addOracle [\"NiNmXL8FjEUEs1nfX9uHFBNaenxDHJtmuB\"]"
echo "   invoke 0xc14ffc3f28363fe59645873b28ed3ed8ccb774cc setMinOracles [1]"
echo ""
echo "2. Test oracle:"
echo "   dotnet run --project src/PriceFeed.Console"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "FILES READY FOR DEPLOYMENT:"
echo "  ✅ $(pwd)/deployment-files/PriceFeed.Oracle.nef"
echo "  ✅ $(pwd)/deployment-files/PriceFeed.Oracle.manifest.json"
echo ""