#!/bin/bash
# Simple deployment helper script

echo "🚀 Neo N3 Price Feed - Deployment Helper"
echo "========================================"
echo ""
echo "📋 Your TestNet Deployment Information:"
echo ""
echo "Master Account Details:"
echo "  Address: NTmHjwiadq4g3VHpJ5FQigQcD4fF5m8TyX"
echo "  Private Key (WIF): KzjaqMvqzF1uup6KrTKRxTgjcXE7PbKLRH84e6ckyXDt3fu7afUb"
echo "  Balance: 50 NEO + 50 GAS (TestNet)"
echo ""
echo "TEE Account: NiNmXL8FjEUEs1nfX9uHFBNaenxDHJtmuB"
echo ""
echo "Contract Files:"
echo "  NEF: src/PriceFeed.Contracts/PriceFeed.Oracle.nef"
echo "  Manifest: src/PriceFeed.Contracts/PriceFeed.Oracle.manifest.json"
echo ""
echo "TestNet RPC: http://seed1t5.neo.org:20332"
echo ""
echo "----------------------------------------"
echo ""
echo "🛠️  DEPLOYMENT OPTIONS:"
echo ""
echo "1. OneGate Web Deployment (Easiest):"
echo "   - Go to: https://onegate.space/deploy"
echo "   - Connect wallet using your private key"
echo "   - Upload NEF and manifest files"
echo "   - Deploy to TestNet"
echo ""
echo "2. NeoLine Chrome Extension:"
echo "   - Install from: https://chrome.google.com/webstore/detail/neoline/cphhlgmgameodnhkjdmkpanlelnlohao"
echo "   - Import account with private key"
echo "   - Switch to TestNet"
echo "   - Use dApp connector to deploy"
echo ""
echo "3. Neo Playground (Web IDE):"
echo "   - Go to: https://neo-playground.dev/"
echo "   - Upload your contract files"
echo "   - Deploy to TestNet"
echo ""
echo "----------------------------------------"
echo ""
echo "📝 AFTER DEPLOYMENT:"
echo ""
echo "1. Copy your contract hash from deployment output"
echo ""
echo "2. Update appsettings.json:"
echo "   \"ContractScriptHash\": \"0xYOUR_CONTRACT_HASH\""
echo ""
echo "3. Initialize the contract (use any Neo wallet or CLI):"
echo "   invoke CONTRACT_HASH initialize [\"NTmHjwiadq4g3VHpJ5FQigQcD4fF5m8TyX\",\"NiNmXL8FjEUEs1nfX9uHFBNaenxDHJtmuB\"]"
echo "   invoke CONTRACT_HASH addOracle [\"NiNmXL8FjEUEs1nfX9uHFBNaenxDHJtmuB\"]"
echo "   invoke CONTRACT_HASH setMinOracles [1]"
echo ""
echo "4. Test the workflow:"
echo "   dotnet run --project src/PriceFeed.Console --skip-health-checks"
echo ""
echo "----------------------------------------"
echo ""
echo "💡 Contract is already compiled and ready at:"
ls -la src/PriceFeed.Contracts/*.nef 2>/dev/null || echo "  Contract files not found!"
ls -la src/PriceFeed.Contracts/*.manifest.json 2>/dev/null || echo "  Manifest files not found!"
echo ""
echo "✅ Everything is ready for deployment!"