name: Neo Price Feed Service (TEE)

on:
  schedule:
    # Run once per week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-price-feed:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for attestation
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Price Feed
      run: |
        # Create attestations directory
        mkdir -p attestations

        # Copy accessible configuration for production use
        cp src/PriceFeed.Console/appsettings.accessible.json src/PriceFeed.Console/appsettings.production.json

        # Run the price feed service with accessible APIs
        dotnet run --project src/PriceFeed.Console/PriceFeed.Console.csproj --configuration Release
      env:
        # Accessible API keys (optional - these APIs work without keys)
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
        KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
        COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
        COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
        
        # Fallback APIs (use only if accessible in your region)
        BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
        BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        
        # Neo blockchain configuration
        NEO_RPC_ENDPOINT: ${{ secrets.NEO_RPC_ENDPOINT }}
        CONTRACT_SCRIPT_HASH: ${{ secrets.CONTRACT_SCRIPT_HASH }}
        TEE_ACCOUNT_ADDRESS: ${{ secrets.TEE_ACCOUNT_ADDRESS }}
        TEE_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEE_ACCOUNT_PRIVATE_KEY }}
        MASTER_ACCOUNT_ADDRESS: ${{ secrets.MASTER_ACCOUNT_ADDRESS }}
        MASTER_ACCOUNT_PRIVATE_KEY: ${{ secrets.MASTER_ACCOUNT_PRIVATE_KEY }}
        SYMBOLS: "NEOBTC,NEOUSDT,BTCUSDT,FLMUSDT,ETHUSDT,ADAUSDT"

    - name: Upload Price Feed Attestations
      uses: actions/upload-artifact@v4
      with:
        name: price-feed-attestations
        path: attestations/
        retention-days: 30  # Keep attestations for 30 days

    - name: Generate Build Attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: src/PriceFeed.Console/bin/Release/net9.0/PriceFeed.Console.dll
