name: Run Price Feed Service

on:
  schedule:
    # Run every 10 minutes to keep price feed data fresh
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - testnet

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-price-feed:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout code (for scripts only)
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          scripts

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Log in to Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Initialize contract if needed
      env:
        MASTER_ACCOUNT_PRIVATE_KEY: ${{ secrets.MASTER_ACCOUNT_PRIVATE_KEY }}
        TEE_ACCOUNT_PRIVATE_KEY: ${{ secrets.NEO_TEE_ACCOUNT_PRIVATE_KEY }}
        ORACLE_CONTRACT_HASH: ${{ secrets.ORACLE_CONTRACT_HASH }}
        NEO_RPC_URL: ${{ secrets.NEO_RPC_URL || 'http://seed1t5.neo.org:20332' }}
      run: |
        echo "Checking if contract needs initialization..."
        python scripts/initialize-contract-rpc.py
      continue-on-error: true

    - name: Run Price Feed Service
      env:
        # Account configuration - map from GitHub secrets to expected names
        MASTER_ACCOUNT_ADDRESS: ${{ secrets.MASTER_ACCOUNT_ADDRESS }}
        MASTER_ACCOUNT_PRIVATE_KEY: ${{ secrets.MASTER_ACCOUNT_PRIVATE_KEY }}
        TEE_ACCOUNT_ADDRESS: ${{ secrets.NEO_TEE_ACCOUNT_ADDRESS }}
        TEE_ACCOUNT_PRIVATE_KEY: ${{ secrets.NEO_TEE_ACCOUNT_PRIVATE_KEY }}
        
        # Neo blockchain configuration
        ORACLE_CONTRACT_HASH: ${{ secrets.ORACLE_CONTRACT_HASH || '0xc14ffc3f28363fe59645873b28ed3ed8ccb774cc' }}
        NEO_RPC_URL: ${{ secrets.NEO_RPC_URL || 'http://seed1t5.neo.org:20332' }}
        
        # API configuration
        COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        PRICE_FEED_API_URL: ${{ secrets.PRICE_FEED_API_URL }}
        
        # Processing configuration
        BATCH_SIZE: ${{ vars.BATCH_SIZE || '10' }}
        PRICE_UPDATE_INTERVAL_MINUTES: ${{ vars.PRICE_UPDATE_INTERVAL_MINUTES || '15' }}
        CONTRACT_GAS_FEE: ${{ vars.CONTRACT_GAS_FEE || '0.05' }}
      run: |
        # Try to pull the latest image, fall back to build if not available
        if docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest 2>/dev/null; then
          echo "Using pre-built Docker image"
          # Run the price feed container in continuous mode for 5 minutes with 15-second intervals
          docker run --rm \
            -e MASTER_ACCOUNT_ADDRESS \
            -e MASTER_ACCOUNT_PRIVATE_KEY \
            -e TEE_ACCOUNT_ADDRESS \
            -e TEE_ACCOUNT_PRIVATE_KEY \
            -e ORACLE_CONTRACT_HASH \
            -e NEO_RPC_URL \
            -e COINMARKETCAP_API_KEY \
            -e PRICE_FEED_API_URL \
            -e BATCH_SIZE \
            -e PRICE_UPDATE_INTERVAL_MINUTES \
            -e CONTRACT_GAS_FEE \
            -v ${{ github.workspace }}/logs:/app/logs \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --continuous --duration 5 --interval 15
        else
          echo "Docker image not available. Please run the Build and Publish workflow first."
          echo "To build the image, run: gh workflow run build-and-publish.yml"
          exit 1
        fi
      timeout-minutes: 30

    - name: Test Price Feed Results
      if: success()
      env:
        ORACLE_CONTRACT_HASH: ${{ secrets.ORACLE_CONTRACT_HASH || '0xc14ffc3f28363fe59645873b28ed3ed8ccb774cc' }}
        NEO_RPC_URL: ${{ secrets.NEO_RPC_URL || 'http://seed1t5.neo.org:20332' }}
      run: |
        echo "Testing price feed results..."
        python scripts/test-price-feed.py
      continue-on-error: true

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: price-feed-logs-${{ github.run_id }}
        path: |
          logs/
          *.log
        retention-days: 7