name: Simple Test Workflow

on:
  schedule:
    # Run once per day at 12:00 UTC
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "Hello, world!"
